version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: hotel_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hotel_db
    ports:
      - "5432:5432"
    volumes:
      - ./db-scripts:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data

  api:
    build: 
      context: ./monolith
    # No container_name here so we can scale
    deploy:
      replicas: 3
    # No public ports! Only reachable via Nginx.
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=hotel_db
      - JWT_SECRET=mysecretkeyforhotelbooking
    volumes:
      - pdf_data:/app/pdfs
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: hotel_nginx
    ports:
      - "3000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api

volumes:
  pgdata:
  pdf_data:
