version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: hotel_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hotel_db
    ports:
      - "5432:5432"
    volumes:
      - ./db-scripts:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: hotel_redis
    ports:
      - "6379:6379"

  user-service:
    build: 
      context: ./services/user-service
    deploy:
      replicas: 2 # Scale independently!
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=hotel_db
      - JWT_SECRET=mysecretkeyforhotelbooking
    depends_on:
      - db

  search-service:
    build: 
      context: ./services/search-service
    deploy:
      replicas: 2 # Scale independently!
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=hotel_db
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis

  booking-service:
    build: 
      context: ./services/booking-service
    deploy:
      replicas: 2 # Scale independently!
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=hotel_db
      - JWT_SECRET=mysecretkeyforhotelbooking
      - SEARCH_SERVICE_URL=http://search-service:8080
    volumes:
      - pdf_data:/app/pdfs
    depends_on:
      - db
      - search-service
      - redis

  worker-service:
    build:
      context: ./services/worker-service
    deploy:
      replicas: 1
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=hotel_db
      - REDIS_HOST=redis
    volumes:
      - pdf_data:/app/pdfs
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:latest
    container_name: hotel_nginx
    ports:
      - "3000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - user-service
      - search-service
      - booking-service
      - worker-service

volumes:
  pgdata:
  pdf_data:
