events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        location /api/users/ {
            proxy_pass http://nginx-user;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/search/ {
            proxy_pass http://nginx-search;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/bookings/ {
            proxy_pass http://nginx-booking;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
