events {
    worker_connections 1024;
}

http {
    upstream search_service {
        server search-service:8080;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://search_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
